# Service Config
server:
  port: 8080
  servlet:
    context-path: /api

# DataSource Config
spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          url: jdbc:postgresql://localhost/test?currentSchema=public&stringtype=unspecified
          username: postgres
          password: 1357_Qetu
          driver-class-name: org.postgresql.Driver
    hikari:
      #连接池名
      pool-name: DateHikariCP
      #最小空闲连接数
      minimum-idle: 2
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 60000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 6
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 600000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1

mybatis-plus:
  configuration:
    mapUnderscoreToCamelCase: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

filedata:
  path: .debug
